# Generated by Django 2.0.1 on 2018-02-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20180202_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='post_text',
            field=models.CharField(max_length=500),
        ),
    ]
