# Generated by Django 2.0.1 on 2018-02-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20180202_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crud',
            new_name='Posts',
        ),
    ]
